apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: challenge-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: challenge-gateway
  template:
    metadata:
      labels:
        app: challenge-gateway
    spec:
      priorityClassName: app-normal
      preemptionPolicy: Never
      containers:
        - name: challenge-gateway
          image: quachuoiscontainer/fctf:gateway-v4-demo
          envFrom:
            - configMapRef:
                name: common-be-cm
            - configMapRef:
                name: challenge-gateway-cm
          resources:
            requests:
              cpu: 0.1
              memory: 16Mi
            limits:
              cpu: 0.3
              memory: 64Mi
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: regcred
  revisionHistoryLimit: 3
---
apiVersion: v1
kind: Service
metadata:
  name: challenge-gateway-svc
  namespace: app
spec:
  ports:
    - protocol: TCP
      name: tcp-1337
      port: 1337
      targetPort: 1337
      nodePort: 30037
    - protocol: TCP
      name: http-8080
      port: 8080
      targetPort: 8080
      nodePort: 30038
  selector:
    app: challenge-gateway
  type: NodePort
---