using StackExchange.Redis;

namespace ResourceShared.Utils
{
    /// <summary>
    /// The one place a Redis connection string turns into ConfigurationOptions.
    ///
    /// Parsing the string as-is meant TLS was whatever the string happened to
    /// say: drop "ssl=true" from REDIS_CONNECTION - by editing a secret, by
    /// falling back to a dev value, by copying a connection string that never
    /// had it - and the service connected in cleartext without a word, putting
    /// the ACL password, session state and every cached value on the wire for
    /// anything sharing the path to read. TLS is the default here instead, and
    /// turning it off has to be deliberate.
    /// </summary>
    public static class RedisOptionsFactory
    {
        /// <summary>
        /// Parses <paramref name="connectionString"/> and applies the transport
        /// security defaults. Callers keep setting their own timeout/retry
        /// options on the result.
        /// </summary>
        public static ConfigurationOptions Build(string connectionString)
        {
            var options = ConfigurationOptions.Parse(connectionString);

            // REDIS_ALLOW_PLAINTEXT exists for local development, where Redis
            // runs from docker-compose.dev.yml with no certificate at all.
            if (!options.Ssl && !EnvFlag("REDIS_ALLOW_PLAINTEXT", false))
            {
                options.Ssl = true;
            }

            // Redis in the cluster serves a certificate its own Helm chart
            // generated (tls.autoGenerated), which chains to nothing any client
            // trusts, so validation is skipped unless the deployment supplies a
            // real CA and sets this to false.
            if (options.Ssl && EnvFlag("REDIS_TLS_INSECURE_SKIP_VERIFY", true))
            {
                options.CertificateValidation += (_, _, _, _) => true;
            }

            return options;
        }

        private static bool EnvFlag(string name, bool fallback)
        {
            var raw = Environment.GetEnvironmentVariable(name);
            return string.IsNullOrWhiteSpace(raw)
                ? fallback
                : raw.Equals("true", StringComparison.OrdinalIgnoreCase);
        }
    }
}
