@startuml
|Operator|
start
:Start Challenge;
if (Validation passed?) then (yes)
  :Deploy Challenge;
  :Create Challenge Container;
  if (Deploy success?) then (yes)
    :Create Challenge URL/Token;
    :Notify Contestant;
    :Access Challenge By Token;
    stop
  else (no)
    :Notify Contestant;
    stop
  endif
else (no)
  :Notify Contestant;
  stop
endif
@enduml