@startuml
|Contestant|
start
:Submit Flag;
|Server|
:Validate flag;
if (Flag correct?) then (yes)
  :Add submission record;
  :Stop challenge;
  :Notify Contestant;
  stop
else (no)
  :Increase attempt;
  :Add submission record;
  :Notify Contestant;
  stop
endif
@enduml