services:
  ctfd:
    build: ./FCTF-ManagementPlatform
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - API_URL_CONTROLSERVER=${API_URL_CONTROLSERVER}
      - API_URL_ADMINSERVER=${API_URL_ADMINSERVER}
      - DEPLOYMENT_SERVICE_API=${DEPLOYMENT_SERVICE_API}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - HOST_CACHE=${HOST_CACHE}
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_PORT=${DATABASE_PORT}
      - REDIS_URL=${REDIS_URL}  # Sử dụng tên service `cache`
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
      - ARGO_WORKFLOWS_URL=${ARGO_WORKFLOWS_URL}
      - ARGO_WORKFLOWS_TOKEN=${ARGO_WORKFLOWS_TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_DB=${REDIS_DB}
      - NFS_MOUNT_PATH=${NFS_MOUNT_PATH}
      - UPLOAD_PROVIDER=${UPLOAD_PROVIDER}
    volumes:
      - ./FCTF-ManagementPlatform/CTFd/logs:/var/log/CTFd
      - ./FCTF-ManagementPlatform/CTFd/uploads:/var/uploads
      - ./FCTF-ManagementPlatform:/opt/CTFd:ro
      - ${NFS_MOUNT_PATH}:${NFS_MOUNT_PATH}
    depends_on:
      - db
      - cache
    networks:
      - default

  # nginx:
  #   image: nginx:alpine
  #   depends_on:
  #     - contestant
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - ./ContestantPlatform/dist:/usr/share/nginx/html:ro
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/cert:/etc/nginx/ssl:ro
  #   networks:
  #     - default

  # contestant:
  #   build: ./ContestantPlatform
  #   user: root
  #   restart: always
  #   depends_on:
  #     - ctfd
  #   volumes:
  #     - ./ContestantPlatform/dist:/usr/share/nginx/html:ro
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   networks:
  #     - default

  db:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ./FCTF-ManagementPlatform/data/mysql:/var/lib/mysql
    networks:
      - default
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --max-connection=1000, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    ports:
      - "6379:6379"  # Mở cổng để truy cập từ local
    restart: always
    volumes:
      - ./FCTF-ManagementPlatform/data/redis:/data
    networks:
      - default

  contestant-service:
    build:
      context: ./ControlCenterAndChallengeHostingServer
      dockerfile: ContestantService/Dockerfile
    restart: always
    ports:
      - "5010:5010"
    environment:
     # ASP.NET
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:5010
      # Database & Cache
      - DB_CONNECTION=${DB_CONNECTION}
      - REDIS_CONNECTION=${REDIS_CONNECTION}
      # Service Config
      - SECRET_KEY=${SECRET_KEY}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CONTROL_SERVER_API=${CONTROL_SERVER_API}
      - DEPLOYMENT_SERVICE_API=${DEPLOYMENT_SERVICE_API}
      - NFS_MOUNT_PATH=${NFS_MOUNT_PATH}
      - USE_LOCAL_K8S=${USE_LOCAL_K8S}
      - K8S_NAMESPACE=${K8S_NAMESPACE}
      # Environment
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
    volumes:
      - ${NFS_MOUNT_PATH}:${NFS_MOUNT_PATH}
    depends_on:
      - db
      - cache
    networks:
      - default

  deployment-service:
    build:
      context: ./ControlCenterAndChallengeHostingServer
      dockerfile: DeploymentService/Dockerfile
    restart: always
    ports:
      - "5020:5020"
    environment:
      # ASP.NET
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:5020
      # Database & Cache
      - DB_CONNECTION=${DB_CONNECTION}
      - REDIS_CONNECTION=${REDIS_CONNECTION}
      # Service Config
      - PRIVATE_KEY=${PRIVATE_KEY}
      - USE_LOCAL_K8S=${USE_LOCAL_K8S}
      - K8S_NAMESPACE=${K8S_NAMESPACE}
      - ARGO_WORKFLOWS_URL=${ARGO_WORKFLOWS_URL}
      - ARGO_WORKFLOWS_TOKEN=${ARGO_WORKFLOWS_TOKEN}
      # Environment
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
    depends_on:
      - db
      - cache
    networks:
      - default

networks:
  default:
    driver: bridge  # Sử dụng bridge network mặc định của Docker Compose