services:
  ctfd:
    build: ./FCTF-ManagementPlatform
    user: root
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEPLOYMENT_SERVICE_API=${DEPLOYMENT_SERVICE_API}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - HOST_CACHE=${HOST_CACHE}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_PORT=${DATABASE_PORT}
      - REDIS_URL=${REDIS_URL}
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - REVERSE_PROXY=true
      - ARGO_WORKFLOWS_URL=${ARGO_WORKFLOWS_URL}
      - ARGO_WORKFLOWS_TOKEN=${ARGO_WORKFLOWS_TOKEN}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_DB=${REDIS_DB}
      - NFS_MOUNT_PATH=${NFS_MOUNT_PATH}
      - UPLOAD_PROVIDER=${UPLOAD_PROVIDER}
      - IMAGE_REPO=${IMAGE_REPO}
      - DOCKER_USERNAME=${DOCKER_USERNAME}
      - UP_CHALLENGE_TEMPLATE=${UP_CHALLENGE_TEMPLATE}
    volumes:
      - ./FCTF-ManagementPlatform/CTFd/logs:/var/log/CTFd
      - ./FCTF-ManagementPlatform/CTFd/uploads:/var/uploads
      - ./FCTF-ManagementPlatform:/opt/CTFd
      - /srv/nfs/share:${NFS_MOUNT_PATH}
    depends_on:
      - db
      - cache
    networks:
      - default
    entrypoint: sh -c "export PYTHONUNBUFFERED=1 && export FLASK_APP=CTFd:create_app && export FLASK_ENV=development && python ping.py && flask db upgrade && flask run --host=0.0.0.0 --port=8000 --reload"

  db:
    image: mariadb:10.11
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - ./FCTF-ManagementPlatform/data/mysql:/var/lib/mysql
    networks:
      - default
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --max-connection=1000, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    ports:
      - "6379:6379"  # Mở cổng để truy cập từ local
    restart: always
    volumes:
      - ./FCTF-ManagementPlatform/data/redis:/data
    networks:
      - default

  contestant-be:
    build:
      context: ./ControlCenterAndChallengeHostingServer
      dockerfile: ContestantBE/Dockerfile
    restart: always
    ports:
      - "5010:5010"
    environment:
     # ASP.NET
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:5010
      # Database & Cache
      - DB_CONNECTION=${DB_CONNECTION}
      - REDIS_CONNECTION=${REDIS_CONNECTION}
      # Service Config
      - PRIVATE_KEY=${PRIVATE_KEY}
      - DEPLOYMENT_SERVICE_API=${DEPLOYMENT_SERVICE_API}
      - NFS_MOUNT_PATH=${NFS_MOUNT_PATH}
      - TCP_DOMAIN=${TCP_DOMAIN}
      - START_CHALLENGE_TEMPLATE=${START_CHALLENGE_TEMPLATE}
    volumes:
      - ${NFS_MOUNT_PATH}:${NFS_MOUNT_PATH}
    depends_on:
      - db
      - cache
    networks:
      - default

  deployment-center:
    build:
      context: ./ControlCenterAndChallengeHostingServer
      dockerfile: DeploymentCenter/Dockerfile
    restart: always
    ports:
      - "5020:5020"
    environment:
      # ASP.NET
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:5020
      # Database & Cache
      - DB_CONNECTION=${DB_CONNECTION}
      - REDIS_CONNECTION=${REDIS_CONNECTION}
      # Service Config
      - PRIVATE_KEY=${PRIVATE_KEY}
      - ARGO_WORKFLOWS_URL=${ARGO_WORKFLOWS_URL}
      - ARGO_WORKFLOWS_TOKEN=${ARGO_WORKFLOWS_TOKEN}
      - START_CHALLENGE_TEMPLATE=${START_CHALLENGE_TEMPLATE}
      - CPU_LIMIT=${CPU_LIMIT}
      - CPU_REQUEST=${CPU_REQUEST}
      - MEMORY_LIMIT=${MEMORY_LIMIT}
      - MEMORY_REQUEST=${MEMORY_REQUEST}
      - POW_DIFFICULTY_SECONDS=${POW_DIFFICULTY_SECONDS}
      - KUBECONFIG=/root/.kube/config
      - TCP_DOMAIN=${TCP_DOMAIN}
    volumes:
    - /home/manhhuy/.kube/config:/root/.kube/config:ro
    depends_on:
      - db
      - cache
    networks:
      - default

  deployment-worker:
    build:
      context: ./ControlCenterAndChallengeHostingServer
      dockerfile: DeploymentListener/Dockerfile
    restart: always
    ports:
      - "5030:5030"
    environment:
      # ASP.NET
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:5030
      # Database & Cache
      - DB_CONNECTION=${DB_CONNECTION}
      - REDIS_CONNECTION=${REDIS_CONNECTION}
      # Worker Config
      - PRIVATE_KEY=${PRIVATE_KEY}
      - TCP_DOMAIN=${TCP_DOMAIN}
      - START_CHALLENGE_TEMPLATE=${START_CHALLENGE_TEMPLATE}
      - KUBECONFIG=/root/.kube/config
    volumes:
      - /home/manhhuy/.kube/config:/root/.kube/config:ro
    depends_on:
      - db
      - cache
    networks:
      - default

networks:
  default:
    driver: bridge  # Sử dụng bridge network mặc định của Docker Compose