"""update Foreign Key in Challenge History table

Revision ID: 0c9d81b33b85
Revises: a8ef35fc706d
Create Date: 2026-05-20 14:10:48.464659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9d81b33b85'
down_revision = 'a8ef35fc706d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
