"""empty message

Revision ID: 4a5a042d2c88
Revises: bb0bab94a39a
Create Date: 2024-11-01 14:21:01.749874

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4a5a042d2c88"
down_revision = "bb0bab94a39a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "challenges",
        "time_limit",
        existing_type=mysql.DATETIME(fsp=6),
        type_=sa.Integer(),
        nullable=True,
    )
    op.add_column(
        "challenges", sa.Column("time_finished", sa.DateTime(), nullable=True)
    )
    op.add_column("challenges", sa.Column("start_time", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "challenges",
        "time_limit",
        existing_type=sa.Integer(),
        type_=mysql.DATETIME(fsp=6),
        nullable=True,
    )
    op.drop_column(
        "challenges", sa.Column("time_finished", sa.DateTime(), nullable=True)
    )
    op.drop_column("challenges", sa.Column("start_time", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###
