"""add function to dynamic_challenge

Revision ID: 5051167cc9b8
Revises: e1667c4453e3
Create Date: 2025-06-09 21:45:08.572312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5051167cc9b8'
down_revision = 'e1667c4453e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamic_challenge', sa.Column('function', sa.String(length=32), nullable=True))
    op.drop_constraint('dynamic_challenge_ibfk_1', 'dynamic_challenge', type_='foreignkey')
    op.create_foreign_key(None, 'dynamic_challenge', 'challenges', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dynamic_challenge', type_='foreignkey')
    op.create_foreign_key('dynamic_challenge_ibfk_1', 'dynamic_challenge', 'challenges', ['id'], ['id'])
    op.drop_column('dynamic_challenge', 'function')
    # ### end Alembic commands ###
