"""add action logs table

Revision ID: 50b52f907c49
Revises: c1d5d49a9614
Create Date: 2025-02-25 15:13:29.083708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50b52f907c49'
down_revision = 'c1d5d49a9614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('actionId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actionDate', mysql.DATETIME(), nullable=False),
    sa.Column('actionType', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actionDetail', mysql.VARCHAR(charset='utf8mb4', length=255), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='userId', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('actionId'),
    )
    # ### end Alembic commands ###


def downgrade():
     # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_logs')
    # ### end Alembic commands ###

