"""empty message

Revision ID: 53aab1b72b47
Revises: 4a5a042d2c88
Create Date: 2024-11-12 14:13:22.316355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53aab1b72b47'
down_revision = '4a5a042d2c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('image_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'image_link')
    # ### end Alembic commands ###
