
"""Add deploy_at column

Revision ID: 66f438637939
Revises: d6b84be0f85e
Create Date: 2024-10-23 12:55:28.241886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f438637939'
down_revision = 'd6b84be0f85e'
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deploy_challenge', 'deploy_at')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deploy_challenge', sa.Column('deploy_at', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
