"""empty message

Revision ID: 709723b37b83
Revises: d423c3240c70
Create Date: 2024-12-06 00:14:24.839449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709723b37b83'
down_revision = 'd423c3240c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_team_id', 'users', 'teams', ['team_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_team_id', 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
