"""empty message

Revision ID: 709723b37b83
Revises: d423c3240c70
Create Date: 2024-12-06 00:14:24.839449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709723b37b83'
down_revision = 'd423c3240c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    result = bind.execute(
        "SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'users' "
        "AND COLUMN_NAME = 'team_id' AND REFERENCED_TABLE_NAME = 'teams' LIMIT 1"
    )
    row = result.fetchone()
    if row:
        op.drop_constraint(row[0], 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_team_id', 'users', 'teams', ['team_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_team_id', 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
