"""empty message

Revision ID: 9928384a3a0d
Revises: d80520db88f6
Create Date: 2024-10-27 07:44:39.689262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9928384a3a0d'
down_revision = 'd80520db88f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'last_update')
    # ### end Alembic commands ###
