"""extend argo_outbox

Revision ID: 9a2500d5d2fd
Revises: a623c366d7ac
Create Date: 2026-01-21 23:38:05.296903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2500d5d2fd'
down_revision = 'a623c366d7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('argo_outbox', sa.Column('processing_at', sa.DateTime(), nullable=True))
    op.add_column('argo_outbox', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('argo_outbox', sa.Column('workflow_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('argo_outbox', 'workflow_name')
    op.drop_column('argo_outbox', 'retry_count')
    op.drop_column('argo_outbox', 'processing_at')
    # ### end Alembic commands ###
