"""add argo outbox table

Revision ID: a623c366d7ac
Revises: fa7bd5a9f42f
Create Date: 2026-01-21 21:37:51.028885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a623c366d7ac'
down_revision = 'fa7bd5a9f42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('argo_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('unlocks_unique', table_name='unlocks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unlocks_unique', 'unlocks', ['team_id', 'target'], unique=True)
    op.drop_table('argo_outbox')
    # ### end Alembic commands ###
