"""add argo outbox table

Revision ID: a623c366d7ac
Revises: fa7bd5a9f42f
Create Date: 2026-01-21 21:37:51.028885

"""
from alembic import op
import sqlalchemy as sa


def _has_table(bind, table_name: str) -> bool:
    inspector = sa.inspect(bind)
    return inspector.has_table(table_name)



# revision identifiers, used by Alembic.
revision = 'a623c366d7ac'
down_revision = 'fa7bd5a9f42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    if not _has_table(bind, 'argo_outbox'):
        op.create_table('argo_outbox',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('payload', sa.JSON(), nullable=False),
            sa.Column('status', sa.Integer(), nullable=True),
            sa.Column('expiry', sa.DateTime(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if _has_table(op.get_bind(), 'argo_outbox'):
        op.drop_table('argo_outbox')
    # ### end Alembic commands ###
