"""empty message

Revision ID: c139bc105dbb
Revises: a02c5bf43407
Create Date: 2024-10-21 16:30:26.402477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c139bc105dbb'
down_revision = 'a02c5bf43407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deploy_challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('deploy_state', sa.String(length=255), nullable=False),
    sa.Column('image_name', sa.String(length=255), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('deployment_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('challenges', sa.Column('time_limit', sa.DateTime(), nullable=True))
    op.add_column('challenges', sa.Column('require_deploy', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'require_deploy')
    op.drop_column('challenges', 'time_limit')
    op.drop_table('deploy_challenge')
    # ### end Alembic commands ###
