"""add challenge start tracking and max deploy count

Revision ID: d9f2e8c7b5a3
Revises: c9c3f0a2b1de
Create Date: 2026-02-25 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'd9f2e8c7b5a3'
down_revision = 'c9c3f0a2b1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add max_deploy_count column to challenges table
    op.add_column('challenges', sa.Column('max_deploy_count', sa.Integer(), nullable=True, server_default='0'))
    
    # Create challenge_start_tracking table
    op.create_table('challenge_start_tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name='fk_challenge_start_tracking_challenge_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='fk_challenge_start_tracking_team_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_challenge_start_tracking_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_challenge_start_tracking_user_challenge', 'user_id', 'challenge_id'),
    sa.Index('idx_challenge_start_tracking_team_challenge', 'team_id', 'challenge_id'),
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop challenge_start_tracking table
    op.drop_table('challenge_start_tracking')
    
    # Remove max_deploy_count column from challenges table
    op.drop_column('challenges', 'max_deploy_count')
    
    # ### end Alembic commands ###
