"""Add new topicName Column

Revision ID: e1667c4453e3
Revises: 50b52f907c49
Create Date: 2025-04-01 16:59:53.035229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1667c4453e3'
down_revision = '50b52f907c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_logs', sa.Column('topicName', sa.String(length=255), nullable=True))
    op.alter_column('action_logs', 'userId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action_logs', 'userId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('action_logs', 'topicName')
    # ### end Alembic commands ###
