"""Add pool, sandbox_definition, sandbox_challenge, sandbox_run_tracking tables

Revision ID: e17d77a765d3
Revises: e6326bc7fe5c
Create Date: 2026-05-22 16:42:25.613698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17d77a765d3'
down_revision = 'e6326bc7fe5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sandbox_definition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sandbox_definition_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sandbox_challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['challenges.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sandbox_run_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sandbox_instance_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['challenge_start_tracking.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_admin_audit_logs_actor_id_ts', table_name='admin_audit_logs')
    op.drop_constraint('1', 'awards', type_='foreignkey')
    op.drop_constraint('2', 'awards', type_='foreignkey')
    op.drop_constraint('1', 'tracking', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('1', 'tracking', 'users', ['user_id'], ['id'])
    op.create_foreign_key('2', 'awards', 'users', ['user_id'], ['id'])
    op.create_foreign_key('1', 'awards', 'teams', ['team_id'], ['id'])
    op.create_index('ix_admin_audit_logs_actor_id_ts', 'admin_audit_logs', ['actor_id', 'timestamp'], unique=False)
    op.drop_table('sandbox_run_tracking')
    op.drop_table('sandbox_challenge')
    op.drop_table('sandbox_definition')
    op.drop_table('pool')
    # ### end Alembic commands ###
