"""add challenge versions table

Revision ID: e1a2b3c4d5f6
Revises: d9f2e8c7b5a3
Create Date: 2026-02-26 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a2b3c4d5f6'
down_revision = 'd9f2e8c7b5a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create challenge_versions table
    op.create_table('challenge_versions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('challenge_id', sa.Integer(), nullable=False),
        sa.Column('version_number', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('image_link', sa.Text(), nullable=True),
        sa.Column('deploy_file', sa.String(length=256), nullable=True),
        sa.Column('cpu_limit', sa.Integer(), nullable=True),
        sa.Column('cpu_request', sa.Integer(), nullable=True),
        sa.Column('memory_limit', sa.Integer(), nullable=True),
        sa.Column('memory_request', sa.Integer(), nullable=True),
        sa.Column('use_gvisor', sa.Boolean(), nullable=True),
        sa.Column('max_deploy_count', sa.Integer(), nullable=True, server_default='0'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='0'),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], name='fk_challenge_versions_challenge_id', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_challenge_versions_created_by', ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('idx_challenge_versions_challenge_id', 'challenge_id'),
        sa.Index('idx_challenge_versions_active', 'challenge_id', 'is_active'),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop challenge_versions table
    op.drop_table('challenge_versions')

    # ### end Alembic commands ###
