"""add challenge_difficulty_visibility and limit_challenges to contests

Revision ID: e4c52818cd2a
Revises: e94e23e540c0
Create Date: 2026-05-26 18:49:28.572779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c52818cd2a'
down_revision = 'e94e23e540c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_audit_logs_actor_id_ts', table_name='admin_audit_logs')
    op.drop_constraint('1', 'awards', type_='foreignkey')
    op.drop_constraint('2', 'awards', type_='foreignkey')
    op.add_column('contests', sa.Column('challenge_difficulty_visibility', sa.String(length=32), nullable=False))
    op.add_column('contests', sa.Column('limit_challenges', sa.Integer(), nullable=True))
    op.drop_constraint('1', 'tracking', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('1', 'tracking', 'users', ['user_id'], ['id'])
    op.drop_column('contests', 'limit_challenges')
    op.drop_column('contests', 'challenge_difficulty_visibility')
    op.create_foreign_key('2', 'awards', 'users', ['user_id'], ['id'])
    op.create_foreign_key('1', 'awards', 'teams', ['team_id'], ['id'])
    op.create_index('ix_admin_audit_logs_actor_id_ts', 'admin_audit_logs', ['actor_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###
