"""add max_deploy_count to challenge_versions table

Revision ID: f3c4d5e6a7b8
Revises: e1a2b3c4d5f6
Create Date: 2026-03-04 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c4d5e6a7b8'
down_revision = 'c2f7a1b0c1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'challenge_versions',
        sa.Column('max_deploy_count', sa.Integer(), nullable=True, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge_versions', 'max_deploy_count')
    # ### end Alembic commands ###
