"""add unique constraint to unlocks

Revision ID: fa7bd5a9f42f
Revises: fa7bd5a9f41f
Create Date: 2025-12-03 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7bd5a9f42f'
down_revision = 'a7f3b2c8d1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unlocks_unique', 'unlocks', ['team_id', 'target'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unlocks_unique', 'unlocks', type_='unique')
    # ### end Alembic commands ###
