"""add cooldown to challenges

Revision ID: fa7bd5a9f41f
Revises: 5051167cc9b8
Create Date: 2025-10-22 22:55:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7bd5a9f41f'
down_revision = '5051167cc9b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('cooldown', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'cooldown')
    # ### end Alembic commands ###
