---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: admin-mvc-svc
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: admin-mvc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: contestant-portal-svc
spec:
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 80
  selector:
    app: contestant-portal
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: contestant-be-svc
spec:
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 5010
  selector:
    app: contestant-be
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: deployment-center-svc
spec:
  ports:
    - protocol: TCP
      port: 5020
      targetPort: 5020
  selector:
    app: deployment-center
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: event-listener-svc
spec:
  ports:
    - protocol: TCP
      port: 5030
      targetPort: 5030
  selector:
    app: event-listener
  type: ClusterIP
---