# ============================================================
# SonarQube - FCTF ChallengeGateway (Go)
# ============================================================
sonar.projectKey=FCTF-ChallengeGateway
sonar.projectName=FCTF Challenge Gateway
sonar.projectVersion=1.0

# Host
sonar.host.url=http://localhost:9000

# Source
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**

# Language
sonar.language=go

# Encoding
sonar.sourceEncoding=UTF-8
