# PVC cho service filebrowser (full quyền, gộp 1 claim)

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-shared-pvc
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs-filebrowser-shared-pv
  storageClassName: ""
