apiVersion: v1
kind: Namespace
metadata:
  name: ${CHALLENGE_NAME}
  labels:
    ctf/temporary: "${IS_TEMPORARY}"
    ctf/expireAfter: "${CHALLENGE_TIMEOUT}"
    ctf/kind: "challenge"
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/enforce-version: "latest"
    pod-security.kubernetes.io/audit: "restricted"
    pod-security.kubernetes.io/audit-version: "latest"
    pod-security.kubernetes.io/warn: "restricted"
    pod-security.kubernetes.io/warn-version: "latest"
---
apiVersion: v1
kind: Service
metadata:
  namespace: ${CHALLENGE_NAME}
  name: ${CHALLENGE_NAME}-svc
  labels:
    ctf/kind: "challenge"
spec:
  type: ClusterIP
  selector:
    app: ${CHALLENGE_NAME}
  ports:
    - name: tcp-challenge-nodeport
      protocol: TCP
      port: 3333
      targetPort: ${CONTAINER_PORT}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: challenge-deny-all
  namespace: ${CHALLENGE_NAME}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: challenge-allow-gateway
  namespace: ${CHALLENGE_NAME}
spec:
  podSelector:
    matchLabels:
      app: ${CHALLENGE_NAME}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app: challenge-gateway
      ports:
        - protocol: TCP
          port: ${CONTAINER_PORT}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: challenge-allow-egress
  namespace: ${CHALLENGE_NAME}
spec:
  podSelector:
    matchLabels:
      app: ${CHALLENGE_NAME}
  policyTypes:
    - Egress
  egress:
    # Allow DNS (UDP/TCP 53 to any)
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow Gateway (Response/Connect)
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app: challenge-gateway
    # Allow Internet
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 192.168.0.0/16
              - 172.16.0.0/12
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ${CHALLENGE_NAME}-job
  namespace: ${CHALLENGE_NAME}
spec:
  ttlSecondsAfterFinished: 1800
  template:
    metadata:
      labels:
        app: ${CHALLENGE_NAME}
        ctf/kind: "challenge"
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false # Không gắn token API server
      priorityClassName: batch-low
      preemptionPolicy: Never
      runtimeClassName: gvisor
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: challenge
          image: "${CONTAINER_IMAGE}"
          ports:
            - containerPort: ${CONTAINER_PORT}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            
          readinessProbe:
            tcpSocket:
              port: ${CONTAINER_PORT}
            periodSeconds: 3
            failureThreshold: 3  

          securityContext:
            allowPrivilegeEscalation: false # Không cho escalate privilege
            privileged: false
            runAsNonRoot: true # Không chạy root
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"] #  Bỏ mọi Linux capabilities
          resources:
            ## HIGH NOTATION 
            requests:
              memory: "32Mi"
              cpu: "0.01"
            limits:
              memory: "128Mi"
              cpu: "0.1"
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: global-regcred
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory