tempo:
  enabled: true

  service:
    type: ClusterIP
    port: 4317   # OTLP gRPC

  persistence:
    enabled: true
    size: 20Gi

  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

  config:
    auth_enabled: false

    server:
      http_listen_port: 3100

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:

    ingester:
      lifecycler:
        ring:
          replication_factor: 1

    compactor:
      compaction:
        block_retention: 24h

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
        wal:
          path: /var/tempo/wal
