tempo:
  enabled: true
  priorityClassName: infra-critical

  service:
    type: ClusterIP
    ports:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
      - name: http
        port: 3100
        targetPort: 3100


  persistence:
    enabled: true
    size: 20Gi

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"

  config:
    auth_enabled: false

    server:
      http_listen_port: 3100

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
            http:

    ingester:
      lifecycler:
        ring:
          replication_factor: 1

    querier:
      max_concurrent_queries: 10

    overrides:
      # Guardrails to avoid heavy queries causing OOM.
      max_bytes_per_trace: 20000000
      max_search_duration: 5m
      max_traces_per_user: 2000

    compactor:
      compaction:
        block_retention: 24h

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces
        wal:
          path: /var/tempo/wal
