apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-backend-ingress
  namespace: app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
    - host: apicontestant.sanchoi.iahn.hanoi.vn 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: contestant-be-svc
                port:
                  number: 5010
  tls:
    - hosts:
        - apicontestant.sanchoi.iahn.hanoi.vn 
      secretName: api-backend-tls