apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-backend-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-dev
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
    - host: api.fctf.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: contestant-be-svc
                port:
                  number: 5010
  tls:
    - hosts:
        - api.fctf.site
      secretName: api-backend-tls