apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fctf-chal-29--1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "wsproblem"
  template:
    metadata:
      labels:
        app: "wsproblem"
    spec:
      containers:
      - name: "web-base"
        image: "kind/challenge/web-base:9be28e93a98c4023e979f1faa0eb5d8bc3efb6ce76f3b1448d4ca3b039d903cb"
        env: []
        ports:
        - containerPort: 80
