apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "fctf-chal-28--1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "pwn-101"
  template:
    metadata:
      labels:
        app: "pwn-101"
    spec:
      containers:
      - name: "pwn-base"
        image: "kind/challenge/pwn-base:30c374096af84ef28c073a6a231b2ed68b23755bb7cace99e40e17f668b222f3"
        env: []
        ports:
        - containerPort: 1200
