---
apiVersion: v1
kind: Namespace
metadata:
  name: cron-job
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-temp-namespaces
  namespace: cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cleanup
          priorityClassName: app-normal
          preemptionPolicy: PreemptLowerPriority
          restartPolicy: Never
          containers:
            - name: cleaner
              image: bitnamilegacy/kubectl:1.33.4
              command:
                - /bin/sh
                - -c
                - |
                  echo "[Cleanup] 🕒 Current Time: $(date -u)"
                  echo "[Cleanup] 🧹 Checking for expired namespaces..."
                  
                  # Lấy danh sách các namespace cần xóa và in ra lý do
                  TARGETS=$(kubectl get ns -l ctf/temporary=true -o json | jq -r '
                    .items[] | 
                    select(.metadata.labels["ctf/expireAfter"] | test("m$")) |
                    {
                      name: .metadata.name,
                      created: (.metadata.creationTimestamp | fromdate),
                      expiry: ((.metadata.labels["ctf/expireAfter"] | sub("m$";"") | tonumber) * 60),
                      age: (now - (.metadata.creationTimestamp | fromdate))
                    } | 
                    select(.age > (.expiry + 30)) | .name
                  ')

                  if [ -z "$TARGETS" ]; then
                    echo "[Cleanup] ✨ No expired namespaces found."
                  else
                    for ns in $TARGETS; do
                      echo "[Cleanup] 🗑️ Deleting expired namespace: $ns"
                      kubectl delete ns "$ns" --ignore-not-found=true --wait=false
                    done
                  fi
                  echo "[Cleanup] ✅ Done!"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cleanup
  namespace: cron-job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleanup-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cleanup-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cleanup-role
subjects:
  - kind: ServiceAccount
    name: cleanup
    namespace: cron-job
