apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-from-app-only
  namespace: db
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: redis
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: app