apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-tls
  namespace: db
spec:
  secretName: rabbitmq-tls
  dnsNames:
    - rabbitmq0.fctf.site
  issuerRef:
    name: letsencrypt-dev
    kind: ClusterIssuer