apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-center-sa
  namespace: app
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-center-sa-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces"]
    verbs: ["get", "list", "watch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-center-sa-binding
subjects:
  - kind: ServiceAccount
    name: deployment-center-sa
    namespace: app
roleRef:
  kind: ClusterRole
  name: deployment-center-sa-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-center-argo-workflow-role
  namespace: argo
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtemplates"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-center-argo-workflow-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: deployment-center-sa
    namespace: app
roleRef:
  kind: Role
  name: deployment-center-argo-workflow-role
  apiGroup: rbac.authorization.k8s.io
