apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: deployment-center
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-center
  template:
    metadata:
      labels:
        app: deployment-center
    spec:
      serviceAccountName: deployment-center-sa
      priorityClassName: app-normal
      preemptionPolicy: Never
      containers:
        - name: deployment-center
          image: quachuoiscontainer/fctf:deployment-center-prod-v4.0.0
          ports:
            - name: http-client
              containerPort: 5020
              protocol: TCP
          envFrom:
            - configMapRef:
                name: common-be-cm
            - configMapRef:
                name: deployment-center-cm
            - secretRef:
                name: common-secret
          resources:
            requests:
              cpu: 0.1
              memory: 256Mi
            limits:
              cpu: 0.3
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5020
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5020
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1654
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - NET_RAW
            seLinuxOptions:
              type: container_t
            seccompProfile:
              type: RuntimeDefault
      imagePullSecrets:
        - name: regcred
  revisionHistoryLimit: 3
