apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: deployment-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-consumer
  template:
    metadata:
      labels:
        app: deployment-consumer
    spec:
      priorityClassName: app-normal
      preemptionPolicy: Never
      containers:
        - name: deployment-consumer
          image: quachuoiscontainer/fctf:deployment-consumer-prod-latest
          envFrom:
            - configMapRef:
                name: deployment-consumer-cm
            - secretRef:
                name: deployment-consumer-secret
            - secretRef:
                name: common-private-key-secret
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.2
              memory: 256Mi
          imagePullPolicy: Always
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1654
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - NET_RAW
            seLinuxOptions:
              type: container_t
            seccompProfile:
              type: RuntimeDefault
      imagePullSecrets:
        - name: regcred
  revisionHistoryLimit: 3
