apiVersion: v1
kind: ServiceAccount
metadata:
  name: start-chal-v2-workflow-sa
  namespace: argo
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: up-challenge-workflow-sa
  namespace: argo
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-executor-role
  namespace: argo
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: start-chal-v2-workflow-executor-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: start-chal-v2-workflow-sa
    namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow-executor-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: up-challenge-workflow-executor-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: up-challenge-workflow-sa
    namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow-executor-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: start-chal-v2-workflow-binding
subjects:
  - kind: ServiceAccount
    name: start-chal-v2-workflow-sa
    namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin