apiVersion: v1
kind: ConfigMap
metadata:
  name: common-be-cm
  namespace: app
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  NFS_MOUNT_PATH: "/mnt/nfs/data"
  DEPLOYMENT_SERVICE_API: "http://deployment-center-svc.app.svc.cluster.local:5020"
  ARGO_WORKFLOWS_URL: "http://argo-workflows-server.argo.svc.cluster.local:2746/api/v1/workflows/argo"
  TCP_DOMAIN: "challenge.fctf.mnhduc.site"
  START_CHALLENGE_TEMPLATE: "start-chal-v2-template"
  # RabbitMQ configuration (password stored in Secret)
  RABBIT_HOST: "rabbitmq.db.svc.cluster.local"
  RABBIT_USERNAME: "user"
  RABBIT_PORT: "5672"
  DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: "false"