apiVersion: v1
kind: ConfigMap
metadata:
  name: contestant-be-cm
  namespace: app
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: "false"
  ASPNETCORE_URLS: "http://+:5010"
  NFS_MOUNT_PATH: "/mnt/nfs/data"
  DEPLOYMENT_SERVICE_API: "http://deployment-center-svc.app.svc.cluster.local:5020"
  IpRateLimiting__EnableEndpointRateLimiting: "true"
  IpRateLimiting__StackBlockedRequests: "false"
  IpRateLimiting__RealIpHeader: "X-Forwarded-For"
  IpRateLimiting__ClientIdHeader: "X-ClientId"
  IpRateLimiting__IpPolicyPrefix: "fctf:contestant:ippolicy"
  IpRateLimiting__RateLimitCounterPrefix: "fctf:contestant:ratelimit"
  IpRateLimiting__HttpStatusCode: "429"
  IpRateLimiting__GeneralRules__0__Endpoint: "*"
  IpRateLimiting__GeneralRules__0__Period: "1s"
  IpRateLimiting__GeneralRules__0__Limit: "50"
  IpRateLimiting__GeneralRules__1__Endpoint: "*"
  IpRateLimiting__GeneralRules__1__Period: "1m"
  IpRateLimiting__GeneralRules__1__Limit: "2000"
  IpRateLimitPolicies__IpRules: "[]"