apiVersion: v1
kind: ConfigMap
metadata:
  name: contestant-portal-cm
  namespace: app
data:
  VITE_API_URL: "https://api.fctf.site/contestant-be/api"
  VITE_BASE_GATEWAY: "challenge.fctf.site"
  VITE_HTTP_PORT: "30038"
  VITE_TCP_PORT: "30037"