apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-center-cm
  namespace: app
data:
  ASPNETCORE_URLS: "http://+:5020"
  RABBIT_PRODUCER_HOST: "rabbitmq.db.svc.cluster.local"
  RABBIT_PRODUCER_PORT: "5672"
  RABBIT_PRODUCER_USERNAME: "deployment-producer"
  RABBIT_PRODUCER_VHOST: "fctf_deploy"

  DEPLOYMENT_QUEUE_TIMEOUT_MINUTES: "5"

  POW_DIFFICULTY_SECONDS: "5" 

  LOKI_BASE_URL: "http://loki-stack.monitoring.svc.cluster.local:3100"

  LOKI_QUERY_SELECTOR: "{app=\"challenge-gateway\"}"