apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-center-cm
  namespace: app
data:
  ASPNETCORE_URLS: "http://+:5020"
  OTEL_SERVICE_NAME: "deployment-center"  

  POW_DIFFICULTY_SECONDS: "5" 
