apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-consumer-cm
  namespace: app
data:
  OTEL_SERVICE_NAME: "deployment-consumer"

  ARGO_DEPLOY_TTL_MINUTES: "6"

  BATCH_SIZE: "20"
  MAX_RUNNING_WORKFLOW: "30"
  WORKER_POLL_INTERVAL_SECONDS: "2"