apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-consumer-cm
  namespace: app
data:
  RABBIT_CONSUMER_HOST: "rabbitmq.db.svc.cluster.local"
  RABBIT_CONSUMER_PORT: "5672"
  RABBIT_CONSUMER_USERNAME: "deployment-consumer"
  RABBIT_CONSUMER_VHOST: "fctf_deploy"

  ARGO_DEPLOY_TTL_MINUTES: "6"

  BATCH_SIZE: "20"
  MAX_RUNNING_WORKFLOW: "30"
  WORKER_POLL_INTERVAL_SECONDS: "2"