apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: contestant-portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contestant-portal
  template:
    metadata:
      labels:
        app: contestant-portal
    spec:
      priorityClassName: app-normal
      preemptionPolicy: Never
      containers:
        - name: contestant-portal
          image: quachuoiscontainer/fctf:contestant-portal-prod-v3.10.1
          ports:
            - name: http-client
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: contestant-portal-cm
          resources:
            requests:
              cpu: 0.1
              memory: 100Mi
            limits:
              cpu: 0.15
              memory: 150Mi
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
  revisionHistoryLimit: 3
