# PV cho service contestant-be

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-contestant-be-file-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - noexec
  nfs:
    server: <MASTER_NODE_PRIVATE_IP>
    path: /srv/nfs/share/file
