# PV cho workflow start-challenge

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-start-challenge-template-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - noexec
  nfs:
    server: <MASTER_NODE_PRIVATE_IP>
    path: /srv/nfs/share/start-challenge
