# PV cho workflow up-challenge
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-up-challenge-file-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /run/desktop/mnt/host/c/fctf-data/challenges
    type: DirectoryOrCreate
