apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: event-listener-svc
spec:
  ports:
    - protocol: TCP
      port: 5030
      targetPort: 5030
  selector:
    app: event-listener
  type: ClusterIP
