apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: admin-mvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-mvc
  template:
    metadata:
      labels:
        app: admin-mvc
    spec:
      priorityClassName: app-normal
      preemptionPolicy: Never
      containers:
        - name: admin-mvc
          image: quachuoiscontainer/fctf:admin-mvc-prod-v4.0.0
          ports:
            - name: http-client
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: common-be-cm
            - configMapRef:
                name: admin-mvc-cm
            - secretRef:
                name: admin-mvc-secret
            - secretRef:
                name: common-secret
          resources:
            requests:
              cpu: 0.2
              memory: 512Mi
            limits:
              cpu: 0.5
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          imagePullPolicy: Always
          volumeMounts:
            - name: nfs-shared-data
              mountPath: /mnt/nfs/data
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: nfs-shared-data
          nfs:
            server: 10.148.0.2
            path: /srv/nfs/share
  revisionHistoryLimit: 3
