apiVersion: v1
kind: Secret
metadata:
  name: admin-mvc-secret
  namespace: app
stringData:
  DATABASE_URL: "mysql+pymysql://ctfd-username:5od4k6jgcmobfavNtTCddADlum1agrRUPOhKA0LA3WFiYxckWz@mariadb-headless.db.svc.cluster.local:3306/ctfd"
  SECRET_KEY: "emdungdepzai"
  REDIS_USER: "svc_admin_mvc"
  REDIS_PASS: "AdmMvcRedis2026A"
  REDIS_PORT: "6380"
  REDIS_URL: "rediss://svc_admin_mvc:AdmMvcRedis2026A@redis-headless.db.svc.cluster.local:6379/0"
