apiVersion: v1
kind: Secret
metadata:
  name: admin-mvc-secret
  namespace: app
stringData:
  DATABASE_URL: "mysql+pymysql://ctfd_admin:FzR1BXgQ7FjYzm6d2zu2bOGfHlWQDDuluLj5Skqa8CrUYFH56M@mariadb-headless.db.svc.cluster.local:3306/ctfd"
  SECRET_KEY: "emdungdepzai"
  REDIS_USER: "svc_admin_mvc"
  REDIS_PASS: "AdmMvcRedis2026A"
  REDIS_PORT: "6379"
  REDIS_URL: "redis://svc_admin_mvc:AdmMvcRedis2026A@redis-headless.db.svc.cluster.local:6379/0"
