apiVersion: v1
kind: Secret
metadata:
  name: contestant-be-secret
  namespace: app
stringData:
  DB_CONNECTION: "Server=mariadb-headless.db.svc.cluster.local;Port=3306;Database=ctfd;User=contestant_be;Password=NKtFmlmqOKWCqmAkE8ICZAykAsTwasu5fWxdpvCeEYBgWeNbKS;"
  REDIS_CONNECTION: "redis-headless.db.svc.cluster.local:6379,password=Fctf2025@,defaultDatabase=0"
