apiVersion: v1
kind: Secret
metadata:
  name: contestant-be-secret
  namespace: app
stringData:
  DB_CONNECTION: "Server=mariadb-headless.db.svc.cluster.local;Port=3306;Database=ctfd;User=contestant_be;Password=NKtFmlmqOKWCqmAkE8ICZAykAsTwasu5fWxdpvCeEYBgWeNbKS;"
  REDIS_CONNECTION: "redis-headless.db.svc.cluster.local:6379,user=svc_contestant_be,password=CbeRedis2026A,defaultDatabase=0,ssl=true,sslProtocols=Tls12"
