apiVersion: v1
kind: Secret
metadata:
  name: deployment-center-secret
  namespace: app
stringData:
  DB_CONNECTION: "Server=mariadb-headless.db.svc.cluster.local;Port=3306;Database=ctfd;User=deployment_center;Password=2ePNjWVf2bPhnXA5bKXNMQDkmziaJT9PqDPkaSbmcutzkzUL89;"
  REDIS_CONNECTION: "redis-headless.db.svc.cluster.local:6379,user=svc_deployment_center,password=DpcRedis2026A,defaultDatabase=0,ssl=true,sslProtocols=tls12"
  RABBIT_PASSWORD: "Fctf2025@producer"
