apiVersion: v1
kind: Secret
metadata:
  name: deployment-consumer-secret
  namespace: app
stringData:
  DB_CONNECTION: "Server=mariadb-headless.db.svc.cluster.local;Port=3306;Database=ctfd;User=deployment_consumer;Password=UCEoSbGsU2haYN1jwFPP0JhOBqlGgC1IlociA8i5wIGageGOHF;"
  REDIS_CONNECTION: "redis-headless.db.svc.cluster.local:6379,user=svc_deployment_consumer,password=DpsCRedis2026A,defaultDatabase=0,ssl=true,sslProtocols=tls12"
  RABBIT_PASSWORD: "Fctf2025@consumer"
