apiVersion: v1
kind: Secret
metadata:
  name: deployment-listener-secret
  namespace: app
stringData:
  DB_CONNECTION: "Server=mariadb-headless.db.svc.cluster.local;Port=3306;Database=ctfd;User=deployment_listener;Password=iHOu7LxTV0cggemLl2NfDOY6Qq0u6MgueurDCNfwFcU3Awx47H;"
  REDIS_CONNECTION: "redis-headless.db.svc.cluster.local:6379,password=Fctf2025@,defaultDatabase=0"
