apiVersion: v1
kind: Secret
metadata:
  name: global-regcred
  namespace: argo
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "<REGISTRY_DOMAIN>": {
          "username": "robot$fctf-ci",
          "password": "aJet6hYxBRw3cUOoScSoZ6bslu8cWR4O"
        }
      }
    }
---
# Secret for Kaniko build - referenced by up-challenge workflow
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-creds
  namespace: argo
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "<REGISTRY_DOMAIN>": {
          "username": "robot$fctf-ci",
          "password": "aJet6hYxBRw3cUOoScSoZ6bslu8cWR4O"
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: app
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "<REGISTRY_DOMAIN>": {
          "username": "robot$fctf-ci",
          "password": "aJet6hYxBRw3cUOoScSoZ6bslu8cWR4O"
        }
      }
    }
