apiVersion: v1
kind: Secret
metadata:
  name: global-regcred
  namespace: argo
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.fctf.site": {
          "username": "admin",
          "password": "FCTF@2025"
        }
      }
    }
---
# Secret for Kaniko build - referenced by up-challenge workflow
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-creds
  namespace: argo
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.fctf.site": {
          "username": "admin",
          "password": "FCTF@2025"
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: app
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.fctf.site": {
          "username": "admin",
          "password": "FCTF@2025"
        }
      }
    }
