apiVersion: v1
kind: Secret
metadata:
  name: redis-auth-secret
  namespace: db
type: Opaque
stringData:
  # Default Redis password used by auth.existingSecret/auth.existingSecretPasswordKey.
  redis-password: "Fctf2025@"